// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuWlTwIuNdCCI50e6HYEaWqYtGK8elxI',
    appId: '1:752726308920:web:73b4c4fcfdf49228c30ecd',
    messagingSenderId: '752726308920',
    projectId: 'ecommerceweb-bf2d0',
    authDomain: 'ecommerceweb-bf2d0.firebaseapp.com',
    storageBucket: 'ecommerceweb-bf2d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofbUf-Xgb-qb8sXSMhADfGJ5u0Na_4_g',
    appId: '1:752726308920:android:0342374ed4b9db58c30ecd',
    messagingSenderId: '752726308920',
    projectId: 'ecommerceweb-bf2d0',
    storageBucket: 'ecommerceweb-bf2d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllyA3HSTiDp0yLgqB5exX1GuqxFNq1jY',
    appId: '1:752726308920:ios:23876139514c1faec30ecd',
    messagingSenderId: '752726308920',
    projectId: 'ecommerceweb-bf2d0',
    storageBucket: 'ecommerceweb-bf2d0.appspot.com',
    iosClientId: '752726308920-954vnt1veoplrl2rhp29qh4sgm1m9le2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceWeb',
  );
}
